"""
This module will be used to generate trained model using the discrete
training data generated by training_data_generator_discrete module.
"""

import pickle
from pathlib import Path

import pandas as pd
from sklearn.tree import DecisionTreeClassifier

from training_data_generator_discrete import (
    rot_training_data_file,
    rot_features,
    rot_target,
    pos_training_data_file,
    pos_features,
    pos_target
)


def rot_model_file():
    return "models/decision_tree_rot_discrete.p"


def pos_model_file():
    return "models/decision_tree_pos_discrete.p"


def _train_rot_model():
    data_file = str(Path(__file__).resolve().parents[0]) + "/" + rot_training_data_file()
    df = pd.read_csv(data_file)
    feature_names = rot_features()
    X = df[feature_names]
    y = df[rot_target()]
    clf = DecisionTreeClassifier().fit(X, y)

    model_file = str(Path(__file__).resolve().parents[0]) + "/" + rot_model_file()
    pickle.dump(clf, open(model_file, 'wb'))
    print("Rotational model trained.")


def _train_pos_model():
    data_file = str(Path(__file__).resolve().parents[0]) + "/" + pos_training_data_file()
    df = pd.read_csv(data_file)
    feature_names = pos_features()
    X = df[feature_names]
    y = df[pos_target()]
    clf = DecisionTreeClassifier().fit(X, y)

    model_file = str(Path(__file__).resolve().parents[0]) + "/" + pos_model_file()
    pickle.dump(clf, open(model_file, 'wb'))
    print("Positional model trained.")


if __name__ == "__main__":
    _train_rot_model()
    _train_pos_model()
